name: dexagents
region: nyc1

services:
  - name: backend
    source_dir: backend
    build_command: pip install -r requirements.txt
    run_command: python run.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    http_port: 8000
    health_check:
      http_path: /api/v1/system/health
    envs:
      - key: API_V1_STR
        value: "/api/v1"
      - key: PROJECT_NAME
        value: "DexAgents - Windows PowerShell Agent"
      - key: VERSION
        value: "1.0.0"
      - key: DATABASE_URL
        value: "dexagents.db"
      - key: BACKEND_CORS_ORIGINS
        value: "${_self.PUBLIC_URL},${frontend.PUBLIC_URL}"
      - key: DEFAULT_TIMEOUT
        value: "30"
      - key: MAX_TIMEOUT
        value: "300"
      - key: AGENT_INSTALLER_PATH
        value: "agent_installers"
      - key: TEMP_DIR
        value: "temp"
      - key: PYTHONPATH
        value: "/app"
      - key: ENVIRONMENT
        value: "production"
      - key: PORT
        value: "8000"
      - key: SECRET_KEY
        type: SECRET
        value: "your-secret-key-here-change-in-production"
    routes:
      - path: /api
      - path: /ws

  - name: frontend
    source_dir: frontend
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    http_port: 3000
    health_check:
      http_path: /api/health
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: "${backend.PUBLIC_URL}/api"
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "3000"
    routes:
      - path: /