name: dexagents
region: nyc
services:
  - name: backend
    build_command: echo "No build command"
    run_command: python run.py
    source_dir: backend
    envs:
      - key: API_V1_STR
        value: "/api/v1"
      - key: PROJECT_NAME
        value: "DexAgents - Windows PowerShell Agent"
      - key: VERSION
        value: "1.0.0"
      - key: DATABASE_URL
        value: "dexagents.db"
      - key: BACKEND_CORS_ORIGINS
        value: "${APP_URL}"
      - key: DEFAULT_TIMEOUT
        value: "30"
      - key: MAX_TIMEOUT
        value: "300"
      - key: AGENT_INSTALLER_PATH
        value: "agent_installers"
      - key: TEMP_DIR
        value: "temp"
      - key: PYTHONPATH
        value: "/app"
      - key: ENVIRONMENT
        value: "production"
      - key: SECRET_KEY
        type: SECRET
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
      - path: /ws
  
  - name: frontend
    build_command: npm install && npm run build
    run_command: npm start
    source_dir: frontend
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: "${APP_URL}/api"
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "3000"
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /