# .do/app.yaml
name: dexagents-saas
region: nyc1

services:
  # Backend API
  - name: api
    source_dir: /backend
    github:
      repo: asedra/dex_agent
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: python run.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    routes:
      - path: /api
    envs:
      - key: PORT
        value: "8000"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        value: "https://dexagents-saas-frontend.ondigitalocean.app"

  # Frontend Dashboard  
  - name: frontend
    source_dir: /frontend
    github:
      repo: asedra/dex_agent
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: "https://dexagents-saas-api.ondigitalocean.app"

databases:
  - name: dexagents-postgres
    engine: PG
    version: "14"
    size: basic-xxs
